esp_toml_version = 1.0
firmware_images_url = "https://dl.espressif.com/AE/esp-brookesia/"

supported_apps = [
    "speaker_0_12_5_ctm_echoear_1_2",
    "speaker_0_12_3_ctm_echoear_1_2",
    "speaker_0_12_2_ctm_echoear_1_2",
    "speaker_0_12_0_ctm_echoear_1_2",
    "speaker_openai_0_2_3_ctm_echoear_1_2",
    "speaker_openai_0_2_1_ctm_echoear_1_2",
    "speaker_openai_0_2_0_ctm_echoear_1_2",
    "echoear_1_2_test_0_12_4",
    "echoear_1_2_test_0_12_0",
    "echoear_1_2_touch_update_5c18"
]

[speaker_0_12_5_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_5_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""
description = "EchoEar firmware with Coze agent functionality, hardware version v1.2, software version v0.12.5"

[speaker_0_12_3_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_3_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""
description = "EchoEar firmware with Coze agent functionality, hardware version v1.2, software version v0.12.3"

[speaker_0_12_2_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_2_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""
description = "EchoEar firmware with Coze agent functionality, hardware version v1.2, software version v0.12.2"

[speaker_0_12_0_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_0_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""
description = "EchoEar firmware with Coze agent functionality, hardware version v1.2, software version v0.12.0"

[speaker_openai_0_2_3_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_openai_0_2_3_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""
description = "EchoEar firmware with OpenAI agent functionality, hardware version v1.2, software version v0.2.3"

[speaker_openai_0_2_1_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_openai_0_2_1_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""
description = "EchoEar firmware with OpenAI agent functionality, hardware version v1.2, software version v0.2.1"

[speaker_openai_0_2_0_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_openai_0_2_0_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""
description = "EchoEar firmware with OpenAI agent functionality, hardware version v1.2, software version v0.2.0"

[echoear_1_2_test_0_12_4]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "echoear_1_2_test_0_12_4.bin"
android_app_url = ""
ios_app_url = ""
description = "This firmware is used to test EchoEar hardware functions, hardware version v1.2, software version v0.12.4"

[echoear_1_2_test_0_12_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "echoear_1_2_test_0_12_0.bin"
android_app_url = ""
ios_app_url = ""
description = "This firmware is used to test EchoEar hardware functions, hardware version v1.2, software version v0.12.0"

[echoear_1_2_touch_update_5c18]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "echoear_1_2_touch_update_5c18.bin"
android_app_url = ""
ios_app_url = ""
description = "This firmware is used to upgrade the Echoear screen touch firmware"
