esp_toml_version = 1.0
firmware_images_url = "https://dl.espressif.com/AE/esp-brookesia/"

supported_apps = ["speaker_0_12_0_ctm_echoear_1_2", "echoear_1_2_test_0_12_0"]

[speaker_0_12_2_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_2_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""

[speaker_0_12_0_ctm_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_0_ctm_echoear_1_2.bin"
android_app_url = ""
ios_app_url = ""

[echoear_1_2_test_0_12_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "echoear_1_2_test_0_12_0.bin"
android_app_url = ""
ios_app_url = ""
